apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: argo-wf-cluster
  namespace: ops-it-platforms
spec:
  forProvider:
    location: us-central1
    initialClusterVersion: "1.21"
    nodeConfig:
      machineType: n1-standard-2
    # Other GKE cluster settings...
  providerConfigRef:
    name: gcp-provider
