apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: organizations.registry.cloud.company.com
spec:
  group: cloud.company.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                labels:
                  type: object
                annotations:
                  type: object
                finalizers:
                  type: array
                  items:
                    type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: A human-readable name. Must be unique within a parent Organization.
                  minLength: 1
                parentOrg:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                      enum:
                        - cloud.company.com/v1alpha1
                    kind:
                      type: string
                      enum:
                        - Organization
                    name:
                      type: string
                      minLength: 1
                  required:
                    - apiVersion
                    - kind
                    - name
                  description: Parent organization where the cost center for this organization is specified.
                memberOf:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                        enum:
                          - cloud.company.com/v1alpha1
                      kind:
                        type: string
                        enum:
                          - Organization
                      name:
                        type: string
                        minLength: 1
                  required:
                    - apiVersion
                    - kind
                    - name
                  description: References to organizations that have indirect authority over this organization.
                  default: []
                approvers:
                  type: string
                  description: An ACG group (a group of AD users) or an AGG group (a group of ACGs) containing users who can approve a production change.
                  minLength: 1
                members:
                  type: string
                  description: An ACG or AGG group representing members of this organization.
                  minLength: 1
              required:
                - name
                - ownedBy
                - approvers
                - members
            status:
              type: object
              properties:
                state:
                  type: string
                  description: The current state of the Organization.
                  enum: ["Pending", "Creating", "Ready", "Error"]
                message:
                  type: string
                  description: Any message related to the current state of the Organization.
                lastUpdated:
                  type: string
                  format: date-time
                  description: The last time the status was updated.
                approvers:
                  type: array
                  items:
                    type: string
                  description: List of resolved AD user details for approvers.
                members:
                  type: array
                  items:
                    type: string
                  description: List of resolved AD user details for members.
  scope: Namespaced
  names:
    plural: organizations
    singular: organization
    kind: Organization
    shortNames:
      - org