apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-product
  namespace: ops-it-platforms
data:
  name: Backstage
  description: Platform for building developer portals
  organization: ops-it-platforms-idp
