apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-product
  namespace: ops-it-platforms
data:
  name: Backstage
  description: Platform for building developer portals
  organization: ops-it-platforms-idp
  ingress: |
    - roles/viewer
    - roles/storage.objectViewer
    - roles/pubsub.viewer
  egress: |
    - roles/viewer
    - roles/storage.objectViewer
    - roles/pubsub.viewer
