apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iamuserpermissions.registry.cloud.company.com
spec:
  group: cloud.company.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                labels:
                  type: object
                annotations:
                  type: object
                finalizers:
                  type: array
                  items:
                    type: string
            spec:
              type: object
              properties:
                userEmail:
                  type: string
                  description: Email of the user for whom the IAM permissions are being managed.
                  minLength: 1
                productName:
                  type: string
                  description: Name of the product or project.
                  minLength: 1
                assetNames:
                  type: array
                  items:
                    type: string
                  description: List of assets associated with the product.
                permissions:
                  type: array
                  items:
                    type: string
                  description: List of IAM permissions for the user.
              required:
                - userEmail
                - productName
                - permissions
            status:
              type: object
              properties:
                state:
                  type: string
                  description: The current state of the IAMUserPermissions.
                  enum: ["Pending", "Active", "Error"]
                message:
                  type: string
                  description: Any message related to the current state of the IAMUserPermissions.
                lastUpdated:
                  type: string
                  format: date-time
                  description: The last time the status was updated.
  scope: Namespaced
  names:
    plural: iamuserpermissions
    singular: iamuserpermission
    kind: IAMUserPermission
    shortNames:
      - iamp