apiversion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: products.registry.cloud.company.com
spec:
  group: cloud.company.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                labels:
                  type: object
                annotations:
                  type: object
                finalizers:
                  type: array
                  items:
                    type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Human-readable name of this Product. Must be globally unique.
                  minLength: 1
                description:
                  type: string
                  description: Reader-friendly summary of this Product’s intended purpose.
                  minLength: 1
                organization:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                      enum:
                        - cloud.company.com/v1alpha1
                    kind:
                      type: string
                      enum:
                        - Organization
                    name:
                      type: string
                      minLength: 1
                  required:
                    - apiVersion
                    - kind
                    - name
                  description: Reference to the Organization that this Product belongs to.
              required:
                - name
                - description
                - organization
            status:
              type: object
              properties:
                state:
                  type: string
                  description: The current state of the Product.
                  enum: ["Pending", "Creating", "Ready", "Error"]
                message:
                  type: string
                  description: Any message related to the current state of the Product.
                lastUpdated:
                  type: string
                  format: date-time
                  description: The last time the status was updated.
  scope: Namespaced
  names:
    plural: products
    singular: product
    kind: Product