apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-it-platforms-pipelines-org
  namespace: ops-it-platforms
data:
  name: CICD Pipelines Team
  ownedBy: ops-it-platforms
  approvers: ops-it-platforms-pipelines-approvers
  members: ops-it-platforms-pipelines-members
